--Day5

DROP TABLE IF EXISTS #Day5
DROP TABLE IF EXISTS #OrderedDay5

CREATE TABLE #Day5 (Day5 NVARCHAR(MAX))

BULK INSERT #Day5 FROM 'C:\Temp\AventCalendar\Day5\Day5Data.txt'

Select TOP 1 (
CASE WHEN Right(LEFT(Day5, 1),1) = 'B' THEN 64 ELSE 0 END +
CASE WHEN Right(LEFT(Day5, 2),1) = 'B' THEN 32 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 3),1) = 'B' THEN 16 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 4),1) = 'B' THEN 8 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 5),1) = 'B' THEN 4 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 6),1) = 'B' THEN 2 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 7),1) = 'B' THEN 1 ELSE 0 END) * 8 + (
CASE WHEN RIGHT(LEFT(Day5, 8),1) = 'R' THEN 4 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 9),1) = 'R' THEN 2 ELSE 0 END +
CASE WHEN RIGHT(LEFT(Day5, 10),1) = 'R' THEN 1 ELSE 0 END) AS 'ANSWER 5A'
From #Day5
ORDER by 1 DESC

--5B

Select
	Row_Number() OVER(Order By (Select SeatId) Asc) as 'Row#',
	SeatId - Row_Number() OVER(Order By (Select SeatId) Asc) as 'DIFF',
	SeatId
INTO #OrderedDay5
From (
	Select (
	CASE WHEN Right(LEFT(Day5, 1),1) = 'B' THEN 64 ELSE 0 END +
	CASE WHEN Right(LEFT(Day5, 2),1) = 'B' THEN 32 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 3),1) = 'B' THEN 16 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 4),1) = 'B' THEN 8 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 5),1) = 'B' THEN 4 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 6),1) = 'B' THEN 2 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 7),1) = 'B' THEN 1 ELSE 0 END) * 8 + (
	CASE WHEN RIGHT(LEFT(Day5, 8),1) = 'R' THEN 4 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 9),1) = 'R' THEN 2 ELSE 0 END +
	CASE WHEN RIGHT(LEFT(Day5, 10),1) = 'R' THEN 1 ELSE 0 END) AS 'SeatID'
	From #Day5) AS x


Select TOP 1 (SeatId - 1) as 'ANSWER 5B' From #OrderedDay5 ORDER By DIFF DESC, Row# ASC